pipeline {
    agent any
    environment {
        REGISTRY = "eu.gcr.io/lbg-mea-17"
        VERSION = "v1"
        YOUR_NAME = "DWRJenkinsKubernetes"
        IMAGE_NAME = "dwr-task1"
    }
    stages {
        stage('Build') {
            steps {
                sh "docker build -t $REGISTRY/$IMAGE_NAME:$VERSION Task1"
            }
        }
        stage('Test') {
            steps {
                sh "echo Testing..."
                sh "sleep 5"
                sh "echo PASSED"
            }
        }
        stage('Push') {
            steps {
                sh "gcloud config set account dwr-service-acct@lbg-mea-17.iam.gserviceaccount.com"
                sh "docker push $REGISTRY/$IMAGE_NAME:$VERSION"
            }
        }
        stage('Deploy') {
            steps {
                sh "gcloud config set account dwr-k8s-service@lbg-mea-17.iam.gserviceaccount.com"
                sh "kubectl create ns task1 || true"
                sh "sed -e 's,{{YOUR_NAME}},'$YOUR_NAME',g;' Task1/app-config.yml | tee Task1/app-config.yml"
                sh "kubectl apply -f Task1 --namespace task1"
                sh "sleep 60"
                sh "kubectl get services --namespace task1"
            }
        }
    }
    post {
        always {
            sh "docker system prune -f"
            sh "gcloud config set account null"
        }
        failure {
            sh "gcloud delete ns task1"
        }
    }
}