pipeline {

    agent any

    environment {
        DOCKER_USER="dwr6"
        MYSQL_ROOT_PASSWORD="password123"
    }

    stages {
        stage("Build and Push") {
            steps {
                sh "docker build -t $DOCKER_USER/task2-db Task2/db"
                sh "docker build -t $DOCKER_USER/task2-app Task2/flask-app"
                sh "docker push $DOCKER_USER/task2-db"
                sh "docker push $DOCKER_USER/task2-app"
            }
        }

        stage("Test") {
            steps {
                echo "Testing..."
                echo "Tests Passed"
            }
        }

        stage("Deploy") {
            steps {
                sh "docker network create task2"
                sh "docker run -d --network task2 --name mysql --env MYSQL_ROOT_PASSWORD $DOCKER_USER/task2-db"
                sh "docker run -d --network task2 --name flask-app --env MYSQL_ROOT_PASSWORD $DOCKER_USER/task2-app"
                sh "docker run -d --network task2 --name nginx -p 80:80 --mount type=bind,source=\$(pwd)/Task2/nginx/nginx.conf,target=/etc/nginx/nginx.conf nginx:latest"
            }
        }
    }

    post {
        always {
            sh "docker system prune -f"
        }
    }   
}